// src/storage/dummyEchoes.ts
import { Echo } from "./echoTypes";

export type PublicEcho = Echo & {
  creator: string;
  likes: number;
  thumbnail?: string;
};

export const dummyEchoes: PublicEcho[] = [
  {
    id: "1",
    userId: "user1",
    title: "Sunset Memories",
    duration: 120,
    prompt: "Calm sunset vibe",
    audioUrl: "https://example.com/audio1.mp3",
    createdAt: new Date().toISOString(), // 오늘 업로드 (신규)
    isPublic: true,
    echoScore: 42,
    playCount: 100,
    purchaseCount: 5,
    genre: "lofi",
    isPurchased: true,
    cost: 0,
    creator: "Alice",
    likes: 42,
    thumbnail: "https://picsum.photos/200/200?1",
    boostedUntil: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 부스팅 2일
    likesHistory: [
      { date: "2025-09-14", count: 10 },
      { date: "2025-09-13", count: 15 },
    ],
    emotion: "Happy",
    mood: "Chill",
    rhythm: "Slow",
    style: "Pop",
    sounds: ["Ocean", "Birds"],
    extra: "Instrumental",
  },
  {
    id: "2",
    userId: "user2",
    title: "Ocean Breeze",
    duration: 95,
    prompt: "Ocean waves and breeze",
    audioUrl: "https://example.com/audio2.mp3",
    createdAt: new Date().toISOString(), // 오늘 업로드 (신규)
    isPublic: true,
    echoScore: 30,
    playCount: 50,
    purchaseCount: 2,
    genre: "ambient",
    isPurchased: true,
    cost: 0,
    creator: "Bob",
    likes: 30,
    thumbnail: "https://picsum.photos/200/200?2",
    likesHistory: [
      { date: "2025-09-14", count: 5 },
      { date: "2025-09-12", count: 12 },
    ],
    emotion: "Sad",
    mood: "Romantic",
    rhythm: "Steady",
    style: "Jazz",
    sounds: ["Rain"],
    extra: "Acoustic",
  },
  {
    id: "3",
    userId: "user3",
    title: "Dreamy Nights",
    duration: 200,
    prompt: "Night ambient sounds",
    audioUrl: "https://example.com/audio3.mp3",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10일 전
    isPublic: true,
    echoScore: 80,
    playCount: 200,
    purchaseCount: 15,
    genre: "ambient",
    isPurchased: true,
    cost: 0,
    creator: "Charlie",
    likes: 80,
    thumbnail: "https://picsum.photos/200/200?3",
    likesHistory: [
      { date: "2025-09-14", count: 20 },
      { date: "2025-09-10", count: 30 },
    ],
    emotion: "Anxious",
    mood: "Dark",
    rhythm: "Fast",
    style: "Rock",
    sounds: ["Wind", "Fire"],
    extra: "Electronic",
  },
  {
    id: "4",
    userId: "user4",
    title: "Chill Morning",
    duration: 150,
    prompt: "Morning chill vibes",
    audioUrl: "https://example.com/audio4.mp3",
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(), // 오래된 곡
    isPublic: true,
    echoScore: 55,
    playCount: 120,
    purchaseCount: 8,
    genre: "lofi",
    isPurchased: true,
    cost: 0,
    creator: "Dana",
    likes: 55,
    thumbnail: "https://picsum.photos/200/200?4",
    likesHistory: [
      { date: "2025-08-30", count: 8 },
      { date: "2025-08-25", count: 12 },
    ],
    emotion: "Tired",
    mood: "Chill",
    rhythm: "Groovy",
    style: "Classical",
    sounds: ["Birds"],
    extra: "Instrumental",
  },
  {
    id: "5",
    userId: "user5",
    title: "Fire Beats",
    duration: 180,
    prompt: "Energetic beat drop",
    audioUrl: "https://example.com/audio5.mp3",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 어제
    isPublic: true,
    echoScore: 20,
    playCount: 30,
    purchaseCount: 1,
    genre: "edm",
    isPurchased: true,
    cost: 0,
    creator: "Eve",
    likes: 20,
    thumbnail: "https://picsum.photos/200/200?5",
    likesHistory: [
      { date: "2025-09-14", count: 7 },
      { date: "2025-09-12", count: 10 },
    ],
    emotion: "Angry",
    mood: "Energetic",
    rhythm: "Fast",
    style: "Electronic",
    sounds: ["Fire"],
    extra: "Vocal",
  },
  {
    id: "6",
    userId: "user6",
    title: "Lonely Road",
    duration: 210,
    prompt: "Sad piano and strings",
    audioUrl: "https://example.com/audio6.mp3",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    isPublic: true,
    echoScore: 65,
    playCount: 140,
    purchaseCount: 4,
    genre: "classical",
    isPurchased: true,
    cost: 0,
    creator: "Frank",
    likes: 65,
    thumbnail: "https://picsum.photos/200/200?6",
    likesHistory: [
      { date: "2025-09-14", count: 15 },
      { date: "2025-09-13", count: 5 },
    ],
    emotion: "Moved",
    mood: "Romantic",
    rhythm: "Slow",
    style: "Classical",
    sounds: ["Piano"],
    extra: "Acoustic",
  },
];
